###
POST http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Juan",
  "lastName": "Fernando",
  "isCodementor": true,
  "email": "fernando.nj@gmail.com",
   "whatsAppNumber": "+1 (973) 851-3343",
  "level": "intermediate",
  "serviceType": "individual",
  "rate": 35,
  "tags": ["JavaScript", "Vue.js", "Front-End"]
}


###
POST http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Jay",
  "lastName": "Wilburn",
  "isCodementor": true,
  "email": "jay@dummy.com",
   "whatsAppNumber": "+1 (000) 000-0000",
  "level": "advanced",
  "serviceType": "individual",
  "rate": 30,
  "tags": ["JavaScript", "Vue.js", "HTML", "Front-End"]
}

###
POST http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Tom",
  "lastName": "Doe",
  "isCodementor": true,
  "email": "tom@dummy.com",
   "whatsAppNumber": "+1 (000) 000-0000",
  "level": "intermediate",
  "serviceType": "individual",
  "rate": 40,
  "tags": ["JavaScript", "Front-End"]
}

###
POST http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Maria",
  "lastName": "Anna",
  "isCodementor": true,
  "email": "Maria@dummy.com",
   "whatsAppNumber": "+1 (000) 000-0000",
  "level": "intermediate",
  "serviceType": "individual",
  "rate": 40,
  "tags": ["JavaScript", "Front-End"]
}


###
POST http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Launch",
  "lastName": "Ventures",
  "isCodementor": false,
  "email": "karan@launchventures.co",
   "whatsAppNumber": "+91 98332 19777",
  "level": "advanced",
  "serviceType": "team",
  "rate": 20,
  "tags": ["JavaScript", "Vue.js", "Front-End", "Mongoose", "MongoDB"]
}

###
POST http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Vinted",
  "lastName": "Inc.",
  "isCodementor": false,
  "email": "hello@vinted.com",
   "whatsAppNumber": "+91 12345 12345",
  "level": "advanced",
  "serviceType": "team",
  "rate": 30,
  "tags": ["JavaScript", "Vue.js", "Front-End"]
}
